[general]

[store]
[store.primary]
connection = "postgresql://graph-node:let-me-in@postgres:5432/graph-node"
weight = 1
pool_size = 10

[chains]
ingestor = "block_ingestor_node"

[chains.avalanche]
shard = "primary"
provider = [
    { label = "mainnet1", url = "https://api.avax.network/ext/bc/C/rpc",features = []}
]

[deployment]
[[deployment.rule]]
shard = "primary"
indexers = [ "default" ]